package mmcs.assignment2

fun main(args: Array<String>) {
    val mat = createMatrix(5,5,5)
    mat.set(Cell(2,3),4)
    mat.set(3,4,5)
    println(mat)
    val mat2= transpose(mat)
    println("transpose")
    println(mat2)
    val mat3= rotate(mat)
    println("rotate")
    println(mat3)
    val mat4= mat.plus(mat2)
    println("plus")
    println(mat4)
    val mat5= mat.unaryMinus()
    println("unaryMinus")
    println(mat5)

    val mat6=createMatrix(5,2,5)
    val mat7= mat.times(mat6)
    println("times1")
    println(mat7)


    println("holes")
    val mat8= createMatrix(5,5,0)
    mat8.set(1,2,3)
    mat8.set(2,3,4)
    println(mat8)
    val mat9= findHoles(mat8)
    println(mat9)
    println("\n")

    println("canOpenLock")
    println("скважина")
    val mat10 = createMatrix(5,5,0)
    mat10.set(2,1,1)
    mat10.set(1,1,1)
    mat10.set(4,4,1)
    mat10.set(3,3,1)
    mat10.set(1,1,1)
    mat10.set(1,4,1)
    println(mat10)
    println("ключ")
    val mat11 = createMatrix(2,2,1)
    mat11.set(0,0,0)
    mat11.set(1,1,0)
    println(mat11)
    println(canOpenLock(mat11,mat10))
}
